[package]
name = "rss_gen"
version = "0.1.0"
authors = ["Jo Phillips <joxphillips@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "2.0"
clap = "3.0.0-beta.1"
nom = "5.0"
